USE [master]
GO

/****** Object:  Database [66bit_Burse]    Script Date: 08.11.2016 15:27:27 ******/
DROP DATABASE [66bit_Burse]
GO

/****** Object:  Database [66bit_Burse]    Script Date: 08.11.2016 15:27:27 ******/
CREATE DATABASE [66bit_Burse]
 CONTAINMENT = NONE
 ON  PRIMARY 
 /*
( NAME = N'66bit_Burse', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS2016\MSSQL\DATA\66bit_Burse.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'66bit_Burse_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS2016\MSSQL\DATA\66bit_Burse_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
*/
GO

/*
ALTER DATABASE [66bit_Burse] SET COMPATIBILITY_LEVEL = 130
GO
*/

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [66bit_Burse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [66bit_Burse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [66bit_Burse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [66bit_Burse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [66bit_Burse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [66bit_Burse] SET ARITHABORT OFF 
GO

ALTER DATABASE [66bit_Burse] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [66bit_Burse] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [66bit_Burse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [66bit_Burse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [66bit_Burse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [66bit_Burse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [66bit_Burse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [66bit_Burse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [66bit_Burse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [66bit_Burse] SET  DISABLE_BROKER 
GO

ALTER DATABASE [66bit_Burse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [66bit_Burse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [66bit_Burse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [66bit_Burse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [66bit_Burse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [66bit_Burse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [66bit_Burse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [66bit_Burse] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [66bit_Burse] SET  MULTI_USER 
GO

ALTER DATABASE [66bit_Burse] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [66bit_Burse] SET DB_CHAINING OFF 
GO

ALTER DATABASE [66bit_Burse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [66bit_Burse] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [66bit_Burse] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [66bit_Burse] SET QUERY_STORE = OFF
GO

USE [66bit_Burse]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [66bit_Burse] SET  READ_WRITE 
GO

